 #Covering Tensor basics using TensorFlow

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
# Create a Vector and check dimension
vector = tf.constant([10,10])
vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:

matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,7],
                              [3.,2.],
                              [8.,9.]],
                             dtype=tf.float16)

In [ ]:
another_matrix.ndim

2

In [ ]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12],
                       [13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(1, 6, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Scalar is single number
### Vector is number with direction (eg. wind speed and direction)
### Matri is 2 dimensional array of numbers
### Tensor is an n dimensional of array of numbers

In [ ]:
# Create tensor with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change on of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [ ]:
# Creating Random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2
random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# Shuffle a tensor(valuable when you want to shuffle data)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tensor1 = tf.constant([[1,2],[3,4],[5,6]],dtype=tf.int64)
tensor1.ndim
tf.expand_dims(tensor1,axis=2)

<tf.Tensor: shape=(3, 2, 1), dtype=int64, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])>

In [ ]:
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(3,4,4,5))

random_tensor1 = tf.random.Generator.from_seed(42)
random_tensor1 = random_tensor1.normal(shape=(3,4,4,5))

#tf.reshape(random_tensor1,shape=(5,4,4,3))

transposed_tensor = tf.transpose(random_tensor1)
random_tensor1 , transposed_tensor

random_tensor1 = tf.cast(random_tensor1,tf.float64)
tf.reduce_sum(random_tensor1)

<tf.Tensor: shape=(), dtype=float64, numpy=-7.2681866539642215>

In [ ]:
import numpy as np
tensor50 = tf.constant(np.random.random(50))
tf.argmax(tensor50)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [ ]:
tf.squeeze(tensor50)

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.04478466, 0.18494131, 0.16993917, 0.59057022, 0.63915996,
       0.04207861, 0.08373898, 0.57520283, 0.06572577, 0.1012588 ,
       0.16116864, 0.86765866, 0.00222556, 0.63609448, 0.62708198,
       0.15361147, 0.04461054, 0.99431262, 0.95385185, 0.28435212,
       0.0737797 , 0.56431978, 0.1270092 , 0.77577629, 0.74819468,
       0.15816328, 0.27411017, 0.45355863, 0.8431558 , 0.31850563,
       0.42742571, 0.05081396, 0.01032702, 0.95482397, 0.78370451,
       0.46992833, 0.98586333, 0.76518436, 0.03328561, 0.90323389,
       0.5214125 , 0.03414904, 0.3434189 , 0.54839557, 0.7878708 ,
       0.72026575, 0.97521754, 0.71537539, 0.43481037, 0.12086033])>

In [ ]:
tf.ones([10,7])
tf.zeros(shape=(3,4))

### Turn NumPy arrays into tensors
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

A = tf.constant(numpy_A,shape=(2,3,4))
B = tf.transpose(A)
B

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(B,seed=42,name="images")

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]], dtype=int32)>

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
#rank_4_tensor.shape
#rank_4_tensor.ndim
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][0][0][:]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
# Get various attributes for our tensor
print("Datatype of evert element:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor[0])
print("Elements along the last index:",rank_4_tensor[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor))
print("Total number of elements in our tensor with numpy:",tf.size(rank_4_tensor).numpy())

Datatype of evert element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Elements along the last index: tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor with numpy: 120


In [ ]:
## Indexing Tensors
# Get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element for each dimension from each index except final

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor(2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape , rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 3 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative of tf.newaxis
tf.expand_dims(rank_2_tensor,axis=0) # Expand 0 axis
tf.expand_dims(rank_2_tensor,axis=1) # Expand 1 axis
tf.expand_dims(rank_2_tensor,axis=-1) # Expand last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
### Manipulating tensors
tensor = tf.constant([[10,7],[3,4]])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)
print(tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  0.7]
 [0.3 0.4]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [ ]:
# We can use the tensorflow built-in function
tf.multiply(tensor,10)
tf.add(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 10],
       [ 6,  7]], dtype=int32)>

In [ ]:
# Matrix multiplication
print(tensor)
print('matmul ',tf.matmul(tensor,tensor))
print(' matrix multiplication with @ ',(tensor @ tensor))
print('direct multiplication',tensor * tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
matmul  tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)
 matrix multiplication with @  tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)
direct multiplication tf.Tensor(
[[100  49]
 [  9  16]], shape=(2, 2), dtype=int32)


In [ ]:
# Create a (3,2) tensor 
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

# Create another (3,2) tensor
Y= tf.constant([[7,8],
               [9,10],
                [11,12]])

tf.matmul(X,Y)

InvalidArgumentError: ignored

In [ ]:
# Let's change the shape of Y
print(Y)
tf.reshape(Y,shape=(2,3))

# Multiply X with reshaped Y
X @ tf.reshape(Y,shape=(2,3))

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
print(tf.reshape(X,shape=(2,3)),Y)
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Can do the same with transpose
X , tf.transpose(X) , tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape
X, Y , tf.matmul(tf.transpose(X),Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y
tf.tensordot(tf.transpose(X),Y,axes=1)

# Peform matrix multi beween X and Y
print(tf.matmul(X,tf.transpose(Y)))
print(tf.matmul(X,tf.reshape(Y,shape=(2,3))))

tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)


In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n")
print("Y reshaped to (2,3): ",tf.reshape(Y,shape=(2,3)))
print("Y Transpose :",tf.transpose(Y)) 

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Y Transpose : tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
B = tf.constant([7.,10.023232939239223323],dtype=tf.float32)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7.  , 10.02], dtype=float16)>

In [ ]:
### Aggregating tensors
D = tf.constant([-7,-10])
print('absolute tensor ',D)

agg_tensor = tf.constant(np.random.randint(0,100,size=50))
#agg_tensor, agg_tensor.shape , agg_tensor.ndim
print(agg_tensor)
print('Min ',tf.reduce_min(agg_tensor))
print('Max ',tf.reduce_max(agg_tensor))
print('Mean ',tf.reduce_mean(agg_tensor))
print('Sum ',tf.reduce_sum(agg_tensor))

import tensorflow_probability as tfp
# Variance
print('Variance ',tfp.stats.variance(agg_tensor).numpy())
# Standard Deviation
print('Std Deviation ',tf.math.reduce_std(tf.cast(agg_tensor,dtype=tf.float32))) # Need float as input

absolute tensor  tf.Tensor([ -7 -10], shape=(2,), dtype=int32)
tf.Tensor(
[47 25 31 55 98 46 67 66 59 31  9 39 97 94 35 89  0 73 99 81 95 53 41 60
 76 77 15 92 99  7 43 70  2 91 32 31 90 16 14 73 34 28 45 67 63 46 21 46
 70 12], shape=(50,), dtype=int64)
Min  tf.Tensor(0, shape=(), dtype=int64)
Max  tf.Tensor(99, shape=(), dtype=int64)
Mean  tf.Tensor(53, shape=(), dtype=int64)
Sum  tf.Tensor(2650, shape=(), dtype=int64)
Variance  849
Std Deviation  tf.Tensor(29.141037, shape=(), dtype=float32)


In [ ]:
# Find the variance of agg_tensor
print('Variance ',tf.math.reduce_variance(tf.cast(agg_tensor,dtype=tf.float16)))

Variance  tf.Tensor(849.5, shape=(), dtype=float16)


In [ ]:
# Creating a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)
F[tf.argmax(F)]
tf.reduce_max(F)
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# Find the positional minimum
tf.argmin(F)
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
### Squeezing a tensor
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
print(G)
print('G Squeezed ',tf.squeeze(G))

tf.Tensor(
[[[[[0.803156   0.49777734 0.37054038 0.9118674  0.637642   0.18209696
     0.63791955 0.27701473 0.04227114 0.84219384 0.90637195 0.222556
     0.9198462  0.68789077 0.42705178 0.878158   0.6943959  0.46567595
     0.52925766 0.33019018 0.12754858 0.16153514 0.5085137  0.44301772
     0.35205877 0.8969147  0.24940813 0.76328313 0.85935795 0.08480155
     0.20418596 0.28848922 0.65142167 0.7106751  0.8695041  0.23745108
     0.6688912  0.7115667  0.21899498 0.7702793  0.45055628 0.95493364
     0.71695936 0.98945487 0.1511141  0.06240606 0.15209746 0.99522185
     0.7830266  0.10455871]]]]], shape=(1, 1, 1, 1, 50), dtype=float32)
G Squeezed  tf.Tensor(
[0.803156   0.49777734 0.37054038 0.9118674  0.637642   0.18209696
 0.63791955 0.27701473 0.04227114 0.84219384 0.90637195 0.222556
 0.9198462  0.68789077 0.42705178 0.878158   0.6943959  0.46567595
 0.52925766 0.33019018 0.12754858 0.16153514 0.5085137  0.44301772
 0.35205877 0.8969147  0.24940813 0.76328313 0.85935795 0.0848

In [ ]:
## Create 4 rank tensor
tensor4 = tf.constant(tf.random.uniform(shape=[15]),shape=(1,3,1,5))
print('tensor4',tensor4)
print('squeeze tensor4 ',tf.squeeze(tensor4))

tensor4 tf.Tensor(
[[[[0.5979867  0.21026528 0.84115803 0.6577226  0.2851386 ]]

  [[0.09847593 0.9034562  0.2376492  0.29771054 0.11016846]]

  [[0.7843586  0.8114835  0.06177711 0.68540204 0.58411586]]]], shape=(1, 3, 1, 5), dtype=float32)
squeeze tensor4  tf.Tensor(
[[0.5979867  0.21026528 0.84115803 0.6577226  0.2851386 ]
 [0.09847593 0.9034562  0.2376492  0.29771054 0.11016846]
 [0.7843586  0.8114835  0.06177711 0.68540204 0.58411586]], shape=(3, 5), dtype=float32)


In [ ]:
### One-hot encoding tensors
some_list = [0,1,2,3] # could be red , green ,blue , purple
tf.one_hot(some_list,depth=4)
# tf.one_hot(some_list,depth=4,on_value="on",off_value="off")


In [ ]:
# Create a new tensor

H = tf.range(1,25)
print(tf.sqrt(tf.cast(H,dtype=tf.float32)))
print(tf.math.log(tf.cast(H,dtype=tf.float32)))

tf.Tensor(
[0.99999994 1.4142134  1.7320508  1.9999999  2.236068   2.4494896
 2.6457512  2.8284268  2.9999998  3.1622777  3.3166244  3.4641016
 3.6055508  3.7416573  3.8729832  3.9999998  4.1231055  4.2426405
 4.3588986  4.472136   4.5825753  4.6904154  4.795831   4.898979  ], shape=(24,), dtype=float32)
tf.Tensor(
[0.        0.6931472 1.0986123 1.3862944 1.609438  1.7917595 1.9459102
 2.0794415 2.1972246 2.3025851 2.3978953 2.4849067 2.5649493 2.6390574
 2.7080503 2.7725887 2.8332133 2.8903718 2.944439  2.9957323 3.0445225
 3.0910425 3.1354942 3.1780539], shape=(24,), dtype=float32)


In [ ]:
# Tensors and Numpy
J = tf.constant(np.array([3.,7.,10.]))

# Convert our tensor back to Numpy array
np.array(J) , type(np.array(J))

print(J.numpy())
print(J.numpy()[0])

[ 3.  7. 10.]
3.0


In [ ]:
# Default types 
nummpy_J = tf.constant(np.array([3.,2.,5.]))
tensor_J = tf.constant([3.,2.,5.])

nummpy_J.dtype , tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
# Finding access to GPUs
import tensorflow as tf
print(tf.config.list_physical_devices())
print(tf.config.list_physical_devices("GPU"))
print(tf.config.list_physical_devices("CPU"))
!nvidia-smi

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
Mon Jun  6 12:54:41 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8     9W /  70W |      3MiB / 15109MiB |     